<?php
namespace NG_RPC\Thrift;

/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


final class IdempotentLevel {
  const idempotent_level_idempotent = 1;
  const idempotent_level_repeat_tolerate = 10;
  const idempotent_level_ensure_once = 50;
  const idempotent_level_none = 100;
  static public $__names = array(
    1 => 'idempotent_level_idempotent',
    10 => 'idempotent_level_repeat_tolerate',
    50 => 'idempotent_level_ensure_once',
    100 => 'idempotent_level_none',
  );
}


